// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5a3d9370-b34c-4439-8385-c1786ed55591",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1mSef4kE5",
    "aws_user_pools_web_client_id": "5o9l9rjr6qul198o6m56cgvcr9",
    "oauth": {},
    "aws_mobile_analytics_app_id": "fdb5324c5dfc4228ae9ac8b31dbacabe",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_reactjs",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ],
    "aws_app_analytics": "enable"
};


export default awsmobile;
